import Head from 'next/head'
import Image from 'next/image'
import styles from '@/styles/Home.module.css'
// import fetchPalette from './api/palette'
import React, { useState, useEffect } from "react";


export default function Home() {
  const [palette, setPalette] = useState(null);

  useEffect(() => {
    async function fetchPalette() {
      const res = await fetch("/api/palette");
      const data = await res.json();
      setPalette(data);
    }

    fetchPalette();
  }, []);

  console.log(palette)
  
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        {/* <button onClick={fetchPalette}>fetch</button> */}
        <button>fetch</button>
      </main>
    </>
  )
}
